add render card to main
MikoreVikt/team-project-filmoteka pull request #4
Opened 2022-11-25 19:47 UTC by Oksana-Pak

2022-11-25 20:06 UTC, OleksiiChernii requested changes

2022-11-25 20:06 UTC, OleksiiChernii commented on src/js/main-render.js
> +      return genres.find(genre => genre.id === id).name;
Якщо find не знайде по id то буде undefined і в ньому буде читати поле name що викличе помилку

2022-11-25 20:06 UTC, OleksiiChernii commented on src/js/main-render.js
> +      throw new Error(response.status);
Всі місця де створюєш еррор треба його обробляти

2022-11-26 11:32 UTC, OleksiiChernii approved these changes

2022-11-26 12:36 UTC, MikoreVikt approved these changes

2022-11-26 12:36 UTC, merged